export const statusOption = ["Done", "In Processing", "Testing", "Deployed"];
export const bloodGroupOptions = [
  "O+",
  "O",
  "O-",
  "A+",
  "A",
  "A-",
  "B+",
  "B",
  "B-",
  "AB+",
  "AB",
  "AB-",
];
export const maritalStatusOptions = [
  "Single",
  "Married",
  "Widowed",
  "Separated",
];

export const newHolidays = [
  {
    name: "date",
    label: "Date",
    type: "date",
    value: "",
  },
  {
    name: "occasion",
    label: "Occasion",
    type: "text",
    value: "",
  },
];

export const selectTech = [
  "Ror",
  "Django",
  "React",
  "Angular",
  "Node",
  "Angular+Node",
  "React+Node",
  "Flask",
  "Vuejs",
  "Qa Manual",
  "Qa Auto",
  "Javascript",
];

export const selectStatus = [
  "Unassigned",
  "Assigned",
  "Completed",
  "Cracked",
  "Rescheduled",
  "Not Done",
  "Canceled",
  "Not Clear",
];
export const selectPriority = ["High", "Medium", "Low"];
export const selectMode = ["Online", "Offline"];
export const leaveType = [
  "Paid Leave",
  "Comp Off",
  "Optional Leave",
  "Casual Leave",
];

export const changeStatus = [
  "I am avialable for any new work",
  "I am busy for assigned work",
  "I am available partially",
];
export const skillOptions = [
  "Python",
  "ROR",
  "React Native",
  "Angularjs1",
  "Go lang",
  "GO",
  "Reactjs",
  "Php",
  "Ruby",
  "Angularjs2",
  "Shopify",
  "NodeJs",
  "ExpressJs",
  "Designing Work",
  "postgres",
  "Rails",
  "Flask",
  "eve",
  "mongodb",
  "javascript",
  "jquery",
  "elastic search",
  "stimulasjs",
  "Data Science",
  "Data Analytics",
  "Saleor",
  "Django",
  "angular7",
  "bootstrap",
  "Java",
  "Advance Java",
  "Mysql",
  "Typescript",
  "aws",
  "django rest framework",
  "html",
  "css",
  "ajax",
  "EmberJs",
  "Logical",
  "Personality",
  "c",
  "c++",
  "wordpress",
  "jsp",
  "c#",
  "redis",
  "sql",
  "docker",
  "graphsql",
  "git",
  "Core java",
  "Android",
  "Xml",
  "mabl",
  "CSS3",
  "SCSS",
  "Bootstrap",
  "HTML 5",
  "Dreamweaver",
  "Responsive Site",
  "J-Query",
  "E-mail templates creation",
  "PSD to HTML",
  "Browser Compatibility",
  "webflow",
  "foundation",
  "Wix",
  "Squarespace",
  "photoshop",
  "Redux",
  "DBMS",
  "OS",
  "Data Structure",
  "NextJS",
  "Recruitment",
  "talent acquistion",
  "employee engagement",
  "payroll",
  "onboarding",
  "Documenation Process",
  "administration",
  "scrapy",
  "Firebase",
  "VueJS",
  "svelte js",
  "ci/cd",
  "OOPS",
  "Github",
  "Bitbucket",
  "Stripe Payment Gateway",
  "Heroku",
  "EC2",
  "Ubuntu",
  "Rspec",
  "Unit test",
  "Redis cache",
  "Background Jobs",
  "kafka",
  "microservices",
  "deployment",
  "solar",
  "Google Cloud Platform",
  "agile methodology",
  "kibana",
  "DigitalOcean",
  "Apache Guacamole",
  "Google Cloud",
  "AWS S3 Glacier",
  "celery",
  "Azure",
  "SonarQube",
  "Apache Openmeeting",
  "REST",
  "Alexa skills building",
  "Google Action",
  "AWS",
  "AWS Lambda",
  "AWS EC2",
  "AWS S3",
  "Apache Superset",
  "AWS IAM",
  "AWS DynamoDB",
  "AWS RDS",
  "AWS API Gateway",
  "angular11",
  "postman",
  "flutter",
  "MS Office",
  "MS Excel",
  "communication",
  "team building",
  "Angular",
  "Linux",
  "Apache",
  "handlebars",
  "FI",
  "oracle database",
  "gdal",
  "xd",
  "drf",
  "Graphic Design",
  "UI/UX",
  "XD",
  "Web Design",
  "Figma",
  "Photoshop",
  "Poster Design",
  "Graphics",
].map((label, index) => ({ value: index + 1, label }));

export const emails = [
  {
    value: 1,
    label: "abtiwari@bestpeers.com",
  },
  {
    value: 2,
    label: "robarche@bestpeers.com",
  },
  {
    value: 3,
    label: "lopatel@bestpeers.com",
  },
];
export const totalMonths = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const developerProfile = [
  "UI/UX",
  "Django Developer",
  "React Developer",
  "React Native Developer",
  "ROR Developer",
  "Frontend Developer",
  "Backend Developer",
  "MERN Stack Developer",
];
